# vi-like copy paste, note that the command for paste is `ctrl + b + P`
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# allow mouse drag
setw -g mode-mouse on
set -g mouse-select-window on
set -g mouse on
